apiVersion: chaos.sghaida.io/v1alpha1
kind: FaultInjection
metadata:
  labels:
    app.kubernetes.io/name: fi-operator
    app.kubernetes.io/managed-by: kustomize
  name: faultinjection-sample
spec:
  # TODO(user): Add fields here
